// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incoming_order.proto

#include "incoming_order.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR IncomingOrder::IncomingOrder(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.side_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.limitprice_)*/0
  , /*decltype(_impl_.clientid_)*/0
  , /*decltype(_impl_.quantity_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct IncomingOrderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IncomingOrderDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IncomingOrderDefaultTypeInternal() {}
  union {
    IncomingOrder _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IncomingOrderDefaultTypeInternal _IncomingOrder_default_instance_;
static ::_pb::Metadata file_level_metadata_incoming_5forder_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_incoming_5forder_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_incoming_5forder_2eproto = nullptr;

const uint32_t TableStruct_incoming_5forder_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IncomingOrder, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IncomingOrder, _impl_.limitprice_),
  PROTOBUF_FIELD_OFFSET(::IncomingOrder, _impl_.side_),
  PROTOBUF_FIELD_OFFSET(::IncomingOrder, _impl_.clientid_),
  PROTOBUF_FIELD_OFFSET(::IncomingOrder, _impl_.quantity_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::IncomingOrder)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_IncomingOrder_default_instance_._instance,
};

const char descriptor_table_protodef_incoming_5forder_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024incoming_order.proto\"U\n\rIncomingOrder\022"
  "\022\n\nlimitPrice\030\001 \001(\005\022\014\n\004side\030\002 \001(\t\022\020\n\010cli"
  "entId\030\003 \001(\005\022\020\n\010quantity\030\004 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_incoming_5forder_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_incoming_5forder_2eproto = {
    false, false, 117, descriptor_table_protodef_incoming_5forder_2eproto,
    "incoming_order.proto",
    &descriptor_table_incoming_5forder_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_incoming_5forder_2eproto::offsets,
    file_level_metadata_incoming_5forder_2eproto, file_level_enum_descriptors_incoming_5forder_2eproto,
    file_level_service_descriptors_incoming_5forder_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_incoming_5forder_2eproto_getter() {
  return &descriptor_table_incoming_5forder_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_incoming_5forder_2eproto(&descriptor_table_incoming_5forder_2eproto);

// ===================================================================

class IncomingOrder::_Internal {
 public:
};

IncomingOrder::IncomingOrder(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:IncomingOrder)
}
IncomingOrder::IncomingOrder(const IncomingOrder& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IncomingOrder* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.side_){}
    , decltype(_impl_.limitprice_){}
    , decltype(_impl_.clientid_){}
    , decltype(_impl_.quantity_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.side_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.side_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_side().empty()) {
    _this->_impl_.side_.Set(from._internal_side(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.limitprice_, &from._impl_.limitprice_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.quantity_) -
    reinterpret_cast<char*>(&_impl_.limitprice_)) + sizeof(_impl_.quantity_));
  // @@protoc_insertion_point(copy_constructor:IncomingOrder)
}

inline void IncomingOrder::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.side_){}
    , decltype(_impl_.limitprice_){0}
    , decltype(_impl_.clientid_){0}
    , decltype(_impl_.quantity_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.side_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.side_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

IncomingOrder::~IncomingOrder() {
  // @@protoc_insertion_point(destructor:IncomingOrder)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IncomingOrder::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.side_.Destroy();
}

void IncomingOrder::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IncomingOrder::Clear() {
// @@protoc_insertion_point(message_clear_start:IncomingOrder)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.side_.ClearToEmpty();
  ::memset(&_impl_.limitprice_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.quantity_) -
      reinterpret_cast<char*>(&_impl_.limitprice_)) + sizeof(_impl_.quantity_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IncomingOrder::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 limitPrice = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.limitprice_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string side = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_side();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "IncomingOrder.side"));
        } else
          goto handle_unusual;
        continue;
      // int32 clientId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.clientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 quantity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.quantity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IncomingOrder::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IncomingOrder)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 limitPrice = 1;
  if (this->_internal_limitprice() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_limitprice(), target);
  }

  // string side = 2;
  if (!this->_internal_side().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_side().data(), static_cast<int>(this->_internal_side().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "IncomingOrder.side");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_side(), target);
  }

  // int32 clientId = 3;
  if (this->_internal_clientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_clientid(), target);
  }

  // int32 quantity = 4;
  if (this->_internal_quantity() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_quantity(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IncomingOrder)
  return target;
}

size_t IncomingOrder::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IncomingOrder)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string side = 2;
  if (!this->_internal_side().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_side());
  }

  // int32 limitPrice = 1;
  if (this->_internal_limitprice() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_limitprice());
  }

  // int32 clientId = 3;
  if (this->_internal_clientid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_clientid());
  }

  // int32 quantity = 4;
  if (this->_internal_quantity() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_quantity());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IncomingOrder::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IncomingOrder::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IncomingOrder::GetClassData() const { return &_class_data_; }


void IncomingOrder::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IncomingOrder*>(&to_msg);
  auto& from = static_cast<const IncomingOrder&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:IncomingOrder)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_side().empty()) {
    _this->_internal_set_side(from._internal_side());
  }
  if (from._internal_limitprice() != 0) {
    _this->_internal_set_limitprice(from._internal_limitprice());
  }
  if (from._internal_clientid() != 0) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  if (from._internal_quantity() != 0) {
    _this->_internal_set_quantity(from._internal_quantity());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IncomingOrder::CopyFrom(const IncomingOrder& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IncomingOrder)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IncomingOrder::IsInitialized() const {
  return true;
}

void IncomingOrder::InternalSwap(IncomingOrder* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.side_, lhs_arena,
      &other->_impl_.side_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IncomingOrder, _impl_.quantity_)
      + sizeof(IncomingOrder::_impl_.quantity_)
      - PROTOBUF_FIELD_OFFSET(IncomingOrder, _impl_.limitprice_)>(
          reinterpret_cast<char*>(&_impl_.limitprice_),
          reinterpret_cast<char*>(&other->_impl_.limitprice_));
}

::PROTOBUF_NAMESPACE_ID::Metadata IncomingOrder::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_incoming_5forder_2eproto_getter, &descriptor_table_incoming_5forder_2eproto_once,
      file_level_metadata_incoming_5forder_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::IncomingOrder*
Arena::CreateMaybeMessage< ::IncomingOrder >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IncomingOrder >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
