// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incoming_order.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_incoming_5forder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_incoming_5forder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_incoming_5forder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_incoming_5forder_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_incoming_5forder_2eproto;
class IncomingOrder;
struct IncomingOrderDefaultTypeInternal;
extern IncomingOrderDefaultTypeInternal _IncomingOrder_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::IncomingOrder* Arena::CreateMaybeMessage<::IncomingOrder>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class IncomingOrder final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IncomingOrder) */ {
 public:
  inline IncomingOrder() : IncomingOrder(nullptr) {}
  ~IncomingOrder() override;
  explicit PROTOBUF_CONSTEXPR IncomingOrder(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IncomingOrder(const IncomingOrder& from);
  IncomingOrder(IncomingOrder&& from) noexcept
    : IncomingOrder() {
    *this = ::std::move(from);
  }

  inline IncomingOrder& operator=(const IncomingOrder& from) {
    CopyFrom(from);
    return *this;
  }
  inline IncomingOrder& operator=(IncomingOrder&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IncomingOrder& default_instance() {
    return *internal_default_instance();
  }
  static inline const IncomingOrder* internal_default_instance() {
    return reinterpret_cast<const IncomingOrder*>(
               &_IncomingOrder_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IncomingOrder& a, IncomingOrder& b) {
    a.Swap(&b);
  }
  inline void Swap(IncomingOrder* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IncomingOrder* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IncomingOrder* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IncomingOrder>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IncomingOrder& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IncomingOrder& from) {
    IncomingOrder::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IncomingOrder* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IncomingOrder";
  }
  protected:
  explicit IncomingOrder(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSideFieldNumber = 2,
    kLimitPriceFieldNumber = 1,
    kClientIdFieldNumber = 3,
    kQuantityFieldNumber = 4,
  };
  // string side = 2;
  void clear_side();
  const std::string& side() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_side(ArgT0&& arg0, ArgT... args);
  std::string* mutable_side();
  PROTOBUF_NODISCARD std::string* release_side();
  void set_allocated_side(std::string* side);
  private:
  const std::string& _internal_side() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_side(const std::string& value);
  std::string* _internal_mutable_side();
  public:

  // int32 limitPrice = 1;
  void clear_limitprice();
  int32_t limitprice() const;
  void set_limitprice(int32_t value);
  private:
  int32_t _internal_limitprice() const;
  void _internal_set_limitprice(int32_t value);
  public:

  // int32 clientId = 3;
  void clear_clientid();
  int32_t clientid() const;
  void set_clientid(int32_t value);
  private:
  int32_t _internal_clientid() const;
  void _internal_set_clientid(int32_t value);
  public:

  // int32 quantity = 4;
  void clear_quantity();
  int32_t quantity() const;
  void set_quantity(int32_t value);
  private:
  int32_t _internal_quantity() const;
  void _internal_set_quantity(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:IncomingOrder)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr side_;
    int32_t limitprice_;
    int32_t clientid_;
    int32_t quantity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_incoming_5forder_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IncomingOrder

// int32 limitPrice = 1;
inline void IncomingOrder::clear_limitprice() {
  _impl_.limitprice_ = 0;
}
inline int32_t IncomingOrder::_internal_limitprice() const {
  return _impl_.limitprice_;
}
inline int32_t IncomingOrder::limitprice() const {
  // @@protoc_insertion_point(field_get:IncomingOrder.limitPrice)
  return _internal_limitprice();
}
inline void IncomingOrder::_internal_set_limitprice(int32_t value) {
  
  _impl_.limitprice_ = value;
}
inline void IncomingOrder::set_limitprice(int32_t value) {
  _internal_set_limitprice(value);
  // @@protoc_insertion_point(field_set:IncomingOrder.limitPrice)
}

// string side = 2;
inline void IncomingOrder::clear_side() {
  _impl_.side_.ClearToEmpty();
}
inline const std::string& IncomingOrder::side() const {
  // @@protoc_insertion_point(field_get:IncomingOrder.side)
  return _internal_side();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncomingOrder::set_side(ArgT0&& arg0, ArgT... args) {
 
 _impl_.side_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IncomingOrder.side)
}
inline std::string* IncomingOrder::mutable_side() {
  std::string* _s = _internal_mutable_side();
  // @@protoc_insertion_point(field_mutable:IncomingOrder.side)
  return _s;
}
inline const std::string& IncomingOrder::_internal_side() const {
  return _impl_.side_.Get();
}
inline void IncomingOrder::_internal_set_side(const std::string& value) {
  
  _impl_.side_.Set(value, GetArenaForAllocation());
}
inline std::string* IncomingOrder::_internal_mutable_side() {
  
  return _impl_.side_.Mutable(GetArenaForAllocation());
}
inline std::string* IncomingOrder::release_side() {
  // @@protoc_insertion_point(field_release:IncomingOrder.side)
  return _impl_.side_.Release();
}
inline void IncomingOrder::set_allocated_side(std::string* side) {
  if (side != nullptr) {
    
  } else {
    
  }
  _impl_.side_.SetAllocated(side, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.side_.IsDefault()) {
    _impl_.side_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IncomingOrder.side)
}

// int32 clientId = 3;
inline void IncomingOrder::clear_clientid() {
  _impl_.clientid_ = 0;
}
inline int32_t IncomingOrder::_internal_clientid() const {
  return _impl_.clientid_;
}
inline int32_t IncomingOrder::clientid() const {
  // @@protoc_insertion_point(field_get:IncomingOrder.clientId)
  return _internal_clientid();
}
inline void IncomingOrder::_internal_set_clientid(int32_t value) {
  
  _impl_.clientid_ = value;
}
inline void IncomingOrder::set_clientid(int32_t value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:IncomingOrder.clientId)
}

// int32 quantity = 4;
inline void IncomingOrder::clear_quantity() {
  _impl_.quantity_ = 0;
}
inline int32_t IncomingOrder::_internal_quantity() const {
  return _impl_.quantity_;
}
inline int32_t IncomingOrder::quantity() const {
  // @@protoc_insertion_point(field_get:IncomingOrder.quantity)
  return _internal_quantity();
}
inline void IncomingOrder::_internal_set_quantity(int32_t value) {
  
  _impl_.quantity_ = value;
}
inline void IncomingOrder::set_quantity(int32_t value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:IncomingOrder.quantity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_incoming_5forder_2eproto
