# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/proto/incoming_order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"gateway/proto/incoming_order.proto\"U\n\rIncomingOrder\x12\x12\n\nlimitPrice\x18\x01 \x01(\x05\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x10\n\x08\x63lientId\x18\x03 \x01(\x05\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway.proto.incoming_order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INCOMINGORDER._serialized_start=38
  _INCOMINGORDER._serialized_end=123
# @@protoc_insertion_point(module_scope)
